name: Publish NPM (Manual)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
        description: Release Tag to Publish

jobs:
  validate_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: validate-release
        with:
          script: |
            /** the "core" module does not have access to workflow_dispatch inputs */
            const tag = '${{ inputs.release_tag }}';

            /** Releases don't have a guaranteed order, so we'll have to paginate */
            let exhausted = false;
            let page = 1;
            while (!exhausted) {
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo,
                page,
                per_page: 100,
              });

              console.log(releases)

              const matchingRelease = releases.find(r => r.tag_name === tag);
              if (matchingRelease) {
                core.setOutput('hasRelease', true);
                core.setOutput('isPrerelease', release.prerelease);
                return;
              }

              if (releases.length < 100) {
                exhausted = true;
              } else {
                page++
              }
            }

            core.setOutput('has-release', false);
            core.setOutput('is-prerelease', false);

      - name: Abort
        if: ${{ !steps.validate-release.outputs.has-release }}
        run: |
          { 
            echo "Tag ${{ github.event.inputs.release_tag }} not found."
            exit 1
          }

      - name: Print Output
        run: |
          {
            echo "Has Release: ${{ steps.validate-release.outputs.has-release }}"
            echo "Is Prerelease: ${{ steps.validate-release.outputs.is-prerelease }}"
          }

  # publish_npm:
  #   needs: validate_tag
  #   uses: ./.github/workflows/publish.reusable.yml
  #   with:
  #     release-tag: ${{ github.event.inputs.release_tag }}
  #   secrets: inherit
