name: Publish NPM (Manual)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
        description: Release Tag to Publish

jobs:
  validate_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Input
        run: echo "$INPUT_RELEASE_TAG"

      - uses: actions/github-script@v7
        id: validate-release
        with:
          script: |
            const tag = core.getInput('release_tag', { required: true });

            let exhausted = false;
            let page = 1;
            while (!exhausted) {
              const releases = octokit.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo,
                page,
                per_page: 100,
              });

              const matchingRelease = releases.find(r => r.tag_name === tag);
              if (matchingRelease) {
                core.setOutput('hasRelease', true);
                core.setOutput('isPrerelease', release.prerelease);
                return;
              }

              if (releases.length < 100) {
                exhausted = true;
              } else {
                page++
              }
            }

            core.setOutput('hasRelease', false);
            core.setOutput('isPrerelease', false);

      - name: Abort
        if: ${{ !steps.validate-release.outputs.hasRelease }}
        run: |
          { 
            echo "Tag ${{ github.event.inputs.release_tag }} not found."
            exit 1
          }

      - name: Print Output
        run: |
          {
            echo "Has Release: ${{ steps.validate-release.outputs.hasRelease }}"
            echo "Is Prerelease: ${{ steps.validate-release.outputs.isPrerelease }}"
          }

  # publish_npm:
  #   needs: validate_tag
  #   uses: ./.github/workflows/publish.reusable.yml
  #   with:
  #     release-tag: ${{ github.event.inputs.release_tag }}
  #   secrets: inherit
